### ISSUE TITLE
Task: Remove Liquidity

### ISSUE THREAD

**Issue by Edoumou** [Debond-Protocol/Pair-Contract#11]
# Description

A function that allows users to withdraw their liquidity from the contract. The Bonds issued when the user added the liquidity must be burned.

## Type of change

- [x] check the token is listed
- [x] check the user has liquidity in the Pair contract
- [x] update reserves, price and ratio
- [x] burn bonds
- [x] transfer tokens to the user

# How Has This Been Tested?

tested on Remix. Js unitary tests coming

- [x] Remix tests: add liquidity, check ratios factors, check prices
- [ ] JS mocha chai tests

**Comment by Edoumou** [comment]
Remove liquidity done (@dr-chain).

Reviewers:

@GrandGarcon
@toufic0710
@drikssy
@gqkc

**Comment by GrandGarcon** [comment]
remarks about the removeLiquidity function : 
- i wanted to understand the  internal function _removeLiquidity functions following [line](https://github.com/Debond-Protocol/Pair-Contract/blob/ab27833d3e1b1ff932f9b76511fb289bd2da9a2a/contracts/PairContract.sol#L112) :
`
uint256 reserve0 = reserve[_token0][1];
uint256 reserve1 = reserve[_token1][1];

		require(_amountToken0 <= reserve0, "Not much tokens");
		require(_amountToken1 <= reserve1, "Not much tokens");

		(reserve[_token0][0], reserve[_token1][0]) = (reserve0, reserve1);
`
here you consider the reserve is the mapping of the available  amount of token pairs based on the given pair , so  in the index 1  corresponds to the current liquidity of the token (before the swap) , which is then reduced by the amount0 of the liquidity that user wants to remove , but there is no effect on the reserve[_token0][0] and reserve[_token1][0] always ? just needed to get understanding given in the uniswap implementation thius is basically the seperate function  for getting the reserves. 


- also the line 8th `import "./libraries//PRBMathUD60x18.sol"; ` you can remove the / from the front of the library contract.

**Comment by Edoumou** [comment]
Hello @GrandGarcon 

- The / from the front has been removed since yesterday, I probably didn't push the new version. Thank you, I will.
- The price = l_{token0, token1} / l_{token1, token0} depends on L and 𝝙l, this means that if we want to get the price later from a getter function we need to know the previous reserve L, and the reserve L + 𝝙l. Therefore, the reserve array stores L, and L + 𝝙l.  reserve[_token0][0] and reserve[_token1][0] are updated on line 113

```solidity
	function _removeLiquidity(
		address _token0,
		address _token1,
		uint256 _amountToken0,
		uint256 _amountToken1
	) internal {
		uint256 reserve0 = reserve[_token0][1];
		uint256 reserve1 = reserve[_token1][1];

		require(_amountToken0 <= reserve0, "Not much tokens");
		require(_amountToken1 <= reserve1, "Not much tokens");

		(reserve[_token0][0], reserve[_token1][0]) = (reserve0, reserve1);
		(reserve[_token0][1], reserve[_token1][1]) = (reserve0 - (_amountToken0 * 1 ether), reserve1 - (_amountToken1 * 1 
                ether));
	}
```

In the previous code, the line before the last one update reserve[_token0][0] and reserve[_token1][0] to the reserve of corresponding token, and the last line update the reserve to the amount of token in the list after removing liquidity.

**Comment by toufic0710** [comment]
Hi, I don’t see somewhere where you check if bond is redeemable in you removeLiquidity function?

**Comment by dr-chain** [comment]
@toufic0710 Normally, that should be checked by the bank contract before calling removeLiquidity function. Ofcourse, later on we will have a double-check here but for the moment, it can be added in product backlog.
@Edoumou you can add @toufic0710 's comment as an issue on the product backlog.

**Comment by dr-chain** [comment]
@Edoumou can you link the final version of the file to this issue. I will review it then.
